#!/usr/bin/env python3
"""Generate high-level architecture diagrams for documentation."""

from __future__ import annotations

import textwrap
from pathlib import Path


def _build_service_graph() -> str:
    return textwrap.dedent(
        """
        %% Auto-generated by tools/architecture/derive_diagram.py
        graph LR
            container["infrastructure.container\nServiceContainer"]
            settings["core.settings_service\nSettingsService"]
            event_bus["infrastructure.event_bus\nEventBus"]
            simulation["simulation.service\nTrainingPresetService"]
            materials["graphics.materials.cache\nMaterialCache"]
            orchestrator["core.settings_orchestrator\nSettingsOrchestrator"]

            container -->|resolve| settings
            container -->|resolve| event_bus
            container -->|resolve| simulation
            container -->|resolve| materials
            simulation --> orchestrator
            orchestrator --> settings
            materials --> settings
        """
    ).strip()


def main() -> None:
    repo_root = Path(__file__).resolve().parents[2]
    diagrams_dir = repo_root / "docs" / "diagrams"
    diagrams_dir.mkdir(parents=True, exist_ok=True)
    target = diagrams_dir / "architecture_map.mmd"
    target.write_text(_build_service_graph() + "\n", encoding="utf-8")
    print(f"Generated {target.relative_to(repo_root)}")


if __name__ == "__main__":
    main()
