# Основная конфигурация приложения PneumoStabSim

# Общие настройки приложения
application:
  name: "PneumoStabSim"
  version: "2.0.0"
  title: "Pneumatic Stabilizer Simulator"
  organization: "PneumoStabSim"
  
# Настройки окна
window:
  width: 1200
  height: 800
  minimum_width: 800
  minimum_height: 600
  resizable: true
  centered: true
  
# Настройки 3D визуализации  
visualization:
  backend: "qt_quick_3d"  # qt_quick_3d | opengl_legacy
  rhi_backend: "d3d11"    # d3d11 | opengl | vulkan
  antialiasing: true
  vsync: true
  
# Настройки симуляции
simulation:
  update_rate: 60  # Hz
  physics_timestep: 0.01  # seconds
  max_iterations: 1000
  convergence_tolerance: 1e-6
  
# Настройки пневматики
pneumatics:
  default_pressure: 1.0  # bar
  min_pressure: 0.1
  max_pressure: 10.0
  valve_response_time: 0.05  # seconds
  
# Настройки геометрии
geometry:
  default_units: "SI"  # SI | CGS | Imperial | Mixed
  precision: 3  # decimal places
  auto_update: true
