param(
    [string]$ProjectRoot = (Resolve-Path (Join-Path $PSScriptRoot '..' '..')).Path
)

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest

$utf8NoBom = [System.Text.UTF8Encoding]::new($false)
try {
    [Console]::OutputEncoding = $utf8NoBom
    [Console]::InputEncoding = $utf8NoBom
    $global:OutputEncoding = $utf8NoBom
} catch {
    Write-Verbose 'Unable to configure console encodings for launch script.'
}

if ($Host -and $Host.UI -and $Host.UI.SupportsVirtualTerminal) {
    $PSStyle.OutputRendering = 'Host'
}

if (Get-Module -ListAvailable -Name PSReadLine) {
    try {
        Set-PSReadLineOption -BellStyle None -HistorySearchCursorMovesToEnd:$true -ErrorAction Stop
    } catch {
        Write-Verbose 'Unable to tune PSReadLine options; continuing with defaults.'
    }
}

if (Get-Command chcp -ErrorAction SilentlyContinue) {
    try { chcp 65001 | Out-Null } catch { Write-Verbose 'Failed to set code page to UTF-8 during launch.' }
}

$envFile = Join-Path $ProjectRoot '.vs' 'insiders.environment.json'
if (-not (Test-Path $envFile)) {
    Write-Warning "Environment description '$envFile' was not found. Running initializer."
    $initializer = Join-Path $ProjectRoot 'tools' 'visualstudio' 'initialize_insiders_environment.ps1'
    if (-not (Test-Path $initializer)) {
        throw "Initializer script '$initializer' is missing; cannot prepare launch environment."
    }

    & $initializer -ProjectRoot $ProjectRoot | Out-Null

    if (-not (Test-Path $envFile)) {
        throw "Environment description '$envFile' could not be generated by initializer."
    }
}

$envData = Get-Content $envFile -Encoding UTF8 | ConvertFrom-Json

foreach ($entry in $envData.PSObject.Properties) {
    [System.Environment]::SetEnvironmentVariable($entry.Name, $entry.Value)
    Set-Item -Path env:$($entry.Name) -Value $entry.Value -Force
}

$pythonExe = Join-Path $ProjectRoot '.venv' 'Scripts' 'python.exe'
if (-not (Test-Path $pythonExe)) {
    throw "Python interpreter '$pythonExe' was not found."
}

Write-Host 'Launching PneumoStabSim using Visual Studio Insiders profile...' -ForegroundColor Cyan
& $pythonExe (Join-Path $ProjectRoot 'app.py') @args
